/// Flutter icons Icons_barcode
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons_barcode
///      fonts:
///       - asset: fonts/Icons_barcode.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Icons_barcode {
  Icons_barcode._();

  static const _kFontFam = 'Icons_barcode';
  static const String? _kFontPkg = null;

  static const IconData qrcode = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barcode = IconData(0xf02a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
